const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n||0);
const gb=n=>{const bytes=Number(n)||0;if(bytes<1000)return `${fmt(bytes)} Б`;const units=['КБ','МБ','ГБ','ТБ'];let value=bytes/1000,index=0;while(value>=1000&&index<units.length-1){value/=1000;index++;}return `${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value)} ${units[index]}`;};
const dateTime=v=>v?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=document.querySelector('#account-rows');
const isCdn=location.pathname==='/cdn';
let model=null, editingId=null;

function render(data){
  model=data;const accounts=data.accounts||[],totalCdn=accounts.reduce((n,a)=>n+(a.cdnResources||[]).filter(r=>r.active).length,0);
  const reported=accounts.filter(a=>a.grantSpentRub!=null),spent=reported.reduce((n,a)=>n+(a.grantSpentRub||0),0),remaining=reported.reduce((n,a)=>n+(a.grantRemainingRub||0),0);
  document.querySelector('#summary-accounts').textContent=accounts.length;document.querySelector('#nav-count').textContent=accounts.length;
  document.querySelector('#summary-accounts-note').textContent=accounts.every(a=>!a.error)?'Подключены к конфигурации':'Есть ошибки подключения';
  document.querySelector('#summary-cdn').textContent=totalCdn;document.querySelector('#summary-spent').textContent=reported.length?`${fmt(spent)} ₽`:'—';
  document.querySelector('#summary-spent-note').textContent=reported.length?`из ${fmt(reported.length*4000)} ₽ · ${reported.length} отчётов`:'Отчёт ещё не получен';document.querySelector('#summary-remaining').textContent=reported.length?`${fmt(remaining)} ₽`:'—';
  const state=document.querySelector('#connection-state');state.innerHTML=`<i></i> ${accounts.length?'API · '+accounts.length+' АККАУНТ':'НЕТ АККАУНТОВ'}`;
  document.querySelector('#nav-accounts').classList.toggle('active',!isCdn);document.querySelector('#nav-cdn').classList.toggle('active',isCdn);
  document.querySelector('#page-title').textContent=isCdn?'CDN-ресурсы':'Аккаунты';document.querySelector('#breadcrumb-page').textContent=isCdn?'CDN-ресурсы':'Аккаунты';
  document.querySelector('#page-description').textContent=isCdn?'Список ресурсов и использованный трафик по аккаунтам':'Состояние стартовых грантов и трафика CDN';
  document.querySelector('#table-title').textContent=isCdn?'Все CDN-ресурсы':'Ваши аккаунты';document.querySelector('#table-description').textContent=isCdn?'Каждая строка показывает ресурс, аккаунт и трафик с начала гранта':'Данные с начала действия стартового гранта';
  document.querySelector('.table-card').classList.toggle('cdn-table',isCdn);document.querySelector('#search').placeholder=isCdn?'Поиск CDN или аккаунта':'Поиск аккаунта';
  document.querySelector('#add-account').hidden=isCdn;
  if(isCdn){
    document.querySelector('#table-head').innerHTML='<tr><th>АККАУНТ</th><th>CDN-РЕСУРС</th><th>СТАТУС</th><th>ТРАФИК С НАЧАЛА ГРАНТА</th></tr>';
    const all=accounts.flatMap(a=>(a.cdnResources||[]).map(r=>({account:a,resource:r})));
    rows.innerHTML=all.length?all.map(({account:a,resource:r})=>`<tr><td><button class="account-open" data-id="${esc(a.billingAccountId)}">${esc(a.name)}</button><small class="account-id">${esc(a.billingAccountId)}</small></td><td>${esc(r.name||r.id)}<small class="account-id">ID: ${esc(r.id)}</small></td><td><span class="resource-status ${r.active?'is-active':'is-inactive'}"><i></i>${r.active?'Активен':'Неактивен'}</span></td><td><b>${r.trafficAvailable?gb(r.trafficBytes):'Нет данных'}</b><small class="traffic-breakdown">↓ Клиентам ${r.trafficAvailable?gb(r.edgeBytes):'—'} · ↑ Из источников ${r.trafficAvailable?gb(r.originBytes):'—'}</small></td></tr>`).join(''):'<tr><td colspan="4" class="empty-row">CDN-ресурсы не загружены. Проверьте роли cdn.viewer и доступ сервисного аккаунта.</td></tr>';
    rows.querySelectorAll('.account-open').forEach(button=>button.addEventListener('click',()=>showDetails(button.dataset.id)));
    document.querySelector('.summary-grid').hidden=true;
  }else{
    document.querySelector('.summary-grid').hidden=false;
    document.querySelector('#table-head').innerHTML='<tr><th>АККАУНТ</th><th>CDN-РЕСУРСЫ</th><th>ТРАФИК С НАЧАЛА ГРАНТА</th><th>ИСПОЛЬЗОВАНО</th><th>ОСТАТОК ГРАНТА</th><th>ДО ОКОНЧАНИЯ</th><th>ДЕЙСТВИЕ</th></tr>';
    rows.innerHTML=accounts.length?accounts.map(a=>{
      const left=a.grantRemainingRub,used=a.grantSpentRub,pct=used==null?0:Math.min(100,used/40),resources=a.cdnResources||[];
      const totalAvailable=resources.every(r=>r.trafficAvailable),cdnTotal=totalAvailable?gb(a.trafficBytes):'Нет данных';
      const cdnList=resources.length?`<details class="cdn-details"><summary>Список и трафик ▾</summary><div class="cdn-list">${resources.map(r=>`<div><span title="${esc(r.name)}">${esc(r.name)}</span><b>${r.trafficAvailable?gb(r.trafficBytes):'—'}</b><small>Клиентам ${r.trafficAvailable?gb(r.edgeBytes):'—'} · Источники ${r.trafficAvailable?gb(r.originBytes):'—'}</small></div>`).join('')}</div></details>`:'<small>Ресурсы не загружены</small>';
      const errors=[a.error,a.metricError,a.billingError].filter(Boolean);return `<tr><td><div class="account-cell"><span class="account-avatar">${esc((a.name||'?').slice(0,1).toUpperCase())}</span><div><button class="account-name account-open" data-id="${esc(a.billingAccountId)}">${esc(a.name)}</button><div class="account-id">${esc(a.billingAccountId)}</div></div></div>${errors.length?`<div class="row-error" title="${esc(errors.join(' · '))}">Ошибка синхронизации</div>`:''}</td><td><div class="cdn-cell"><b>${resources.length} ${resources.length===1?'ресурс':'ресурсов'}</b><small>Yandex Cloud CDN</small>${cdnList}</div></td><td><div class="traffic-cell"><b>${cdnTotal}</b><small>с ${esc(a.grantStartDate)}</small></div></td><td><div class="grant-number">${used==null?'Ожидание отчёта':`${fmt(used)} ₽`} <span class="grant-total">/ 4 000 ₽</span></div><div class="grant-bar"><i style="width:${pct}%"></i></div><small class="updated-small">Биллинг: ${dateTime(a.billingUpdatedAt)}</small></td><td><div class="remaining">${left==null?'—':`${fmt(left)} ₽`}</div><div class="account-id">осталось средств</div></td><td><div class="days"><span class="days-ring">${a.daysLeft==null?'—':Math.max(0,a.daysLeft)}</span><span class="days-text">дней<small>до ${esc(a.grantEndDate||'—')}</small></span></div></td><td><button class="edit-account" data-id="${esc(a.billingAccountId)}">Изменить</button></td></tr>`;
    }).join(''):'<tr><td colspan="7" class="empty-row">Добавьте первый аккаунт кнопкой «Добавить аккаунт».</td></tr>';
    rows.querySelectorAll('.account-open').forEach(button=>button.addEventListener('click',()=>showDetails(button.dataset.id)));
    rows.querySelectorAll('.edit-account').forEach(button=>button.addEventListener('click',()=>openEdit(button.dataset.id)));
  }
  document.querySelector('#showing').textContent=isCdn?`Показано ${rows.querySelectorAll('tr').length} ресурсов`:`Показано ${accounts.length} аккаунтов`;
  document.querySelector('#updated').textContent=dateTime(data.lastUpdated);
  const errors=accounts.flatMap(a=>[a.error,a.metricError,a.billingError]).filter(Boolean);const trafficMissing=accounts.some(a=>(a.cdnResources||[]).some(r=>!r.trafficAvailable));document.querySelector('#notice').textContent=errors.length?`Есть ошибки API: ${errors.join(' · ')}`:trafficMissing?'Трафик отображается после появления данных Monitoring; метрики Cloud CDN обновляются примерно раз в 3 минуты.':'Автообновление каждую минуту. Отчёты биллинга обновляются по очереди с учётом лимита API.';
}
async function load(){try{const response=await fetch('/api/dashboard',{cache:'no-store'});if(!response.ok)throw new Error(response.status===401?'Требуется вход в панель.':`Ошибка сервера ${response.status}`);render(await response.json());}catch(error){document.querySelector('#connection-state').innerHTML='<i></i> НЕТ СОЕДИНЕНИЯ';document.querySelector('#notice').textContent=`Не удалось получить данные: ${error.message}`;}}
function showDetails(id){const a=model?.accounts.find(x=>x.billingAccountId===id);if(!a)return;document.querySelector('#detail-title').textContent=a.name;document.querySelector('#detail-id').textContent=`Billing account ID · ${a.billingAccountId}`;const resourceList=a.cdnResources||[];const trafficReady=resourceList.every(r=>r.trafficAvailable);const sent=trafficReady?gb(resourceList.reduce((n,r)=>n+(r.edgeBytes||0),0)):'Нет данных',upstream=trafficReady?gb(resourceList.reduce((n,r)=>n+(r.originBytes||0),0)):'Нет данных';document.querySelector('#detail-stats').innerHTML=`<article><small>Весь трафик CDN</small><b>${trafficReady?gb(a.trafficBytes):'Нет данных'}</b></article><article><small>Отправлено клиентам</small><b>${sent}</b></article><article><small>Загружено из источников</small><b>${upstream}</b></article><article><small>Использовано гранта</small><b>${a.grantSpentRub==null?'Ожидание отчёта':`${fmt(a.grantSpentRub)} ₽`}</b></article><article><small>Остаток гранта</small><b>${a.grantRemainingRub==null?'—':`${fmt(a.grantRemainingRub)} ₽`}</b></article><article><small>Дней до окончания</small><b>${a.daysLeft==null?'—':Math.max(0,a.daysLeft)}</b></article><article><small>Грант действует</small><b>${esc(a.grantStartDate)} — ${esc(a.grantEndDate||'—')}</b></article><article><small>Каталогов</small><b>${(a.folders||[]).length}</b></article>`;document.querySelector('#detail-cdn').innerHTML=resourceList.length?resourceList.map(r=>`<div class="detail-resource"><div><strong>${esc(r.name||r.id)}</strong><small>${esc(r.id)} · клиентам ${r.trafficAvailable?gb(r.edgeBytes):'—'} · из источников ${r.trafficAvailable?gb(r.originBytes):'—'}</small></div><span class="resource-status ${r.active?'is-active':'is-inactive'}"><i></i>${r.active?'Активен':'Неактивен'}</span><b>${r.trafficAvailable?gb(r.trafficBytes):'Нет данных'}</b></div>`).join(''):'<p>CDN-ресурсы не загружены.</p>';const errors=[a.error,a.metricError,a.billingError].filter(Boolean);document.querySelector('#detail-errors').textContent=errors.join(' · ');document.querySelector('#detail-edit').dataset.id=id;document.querySelector('#detail-dialog').showModal();}
function openEdit(id){const a=model.accounts.find(x=>x.billingAccountId===id);if(!a)return;editingId=id;const f=document.querySelector('#account-form');f.elements.name.value=a.name;f.elements.billingAccountId.value=id;f.elements.billingAccountId.disabled=true;f.elements.grantStartDate.value=a.grantStartDate;f.elements.folders.value=(a.folders||[]).map(x=>`${x.cloudId},${x.folderId}`).join('\n');f.elements.keyFile.required=false;document.querySelector('#dialog-title').textContent='Изменить аккаунт';document.querySelector('#key-hint').textContent='Необязательно: загрузите новый JSON-ключ, чтобы заменить текущий.';document.querySelector('#form-error').textContent='';document.querySelector('#account-dialog').showModal();}
function openOverview(kind){
  if(!model)return;const accounts=model.accounts||[],dialog=document.querySelector('#overview-dialog'),title=document.querySelector('#overview-title'),description=document.querySelector('#overview-description'),content=document.querySelector('#overview-content');
  if(kind==='accounts'){
    title.textContent='Все аккаунты';description.textContent=`Подключено аккаунтов: ${accounts.length}`;
    content.innerHTML=accounts.length?accounts.map(a=>`<button class="overview-row overview-account" data-id="${esc(a.billingAccountId)}"><span><b>${esc(a.name)}</b><small>${esc(a.billingAccountId)}</small></span><span>${(a.cdnResources||[]).length} CDN</span><span>${a.grantRemainingRub==null?'Остаток не получен':`${fmt(a.grantRemainingRub)} ₽`}</span></button>`).join(''):'<p>Аккаунтов пока нет.</p>';
  }else if(kind==='cdn'){
    const resources=accounts.flatMap(a=>(a.cdnResources||[]).filter(r=>r.active).map(r=>({account:a,resource:r})));
    title.textContent='Активные CDN-ресурсы';description.textContent=`Активных ресурсов: ${resources.length}`;
    content.innerHTML=resources.length?resources.map(({account:a,resource:r})=>`<div class="overview-row"><button class="overview-link" data-id="${esc(a.billingAccountId)}">${esc(a.name)}</button><span><b>${esc(r.name||r.id)}</b><small>ID: ${esc(r.id)}</small></span><span class="resource-status is-active"><i></i>Активен</span><span>${r.trafficAvailable?gb(r.trafficBytes):'Нет данных'}<small>↓ ${r.trafficAvailable?gb(r.edgeBytes):'—'} · ↑ ${r.trafficAvailable?gb(r.originBytes):'—'}</small></span></div>`).join(''):'<p>Активные CDN-ресурсы не найдены.</p>';
  }else{
    const reported=accounts.filter(a=>a.grantSpentRub!=null);
    title.textContent='Детализация грантов';description.textContent='Стартовый грант 4 000 ₽ действует 60 дней с указанной даты.';
    content.innerHTML=accounts.length?accounts.map(a=>{const used=a.grantSpentRub,remaining=a.grantRemainingRub,pct=used==null?0:Math.min(100,used/40);return `<div class="overview-grant"><div class="overview-grant-head"><b>${esc(a.name)}</b><span>${a.daysLeft==null?'—':Math.max(0,a.daysLeft)} дней осталось</span></div><small>${esc(a.billingAccountId)} · ${esc(a.grantStartDate)} — ${esc(a.grantEndDate||'—')}</small><div class="grant-bar overview-bar"><i style="width:${pct}%"></i></div><div class="overview-values"><span>Использовано <b>${used==null?'Ожидание отчёта':`${fmt(used)} ₽`}</b></span><span>Остаток <b>${remaining==null?'—':`${fmt(remaining)} ₽`}</b></span><span>Отчётов биллинга <b>${a.billingUpdatedAt?dateTime(a.billingUpdatedAt):'нет'}</b></span></div></div>`}).join(''):'<p>Аккаунтов пока нет.</p>';
    if(!reported.length&&accounts.length)description.textContent+=' Данные расходов ещё не получены из Billing.';
  }
  content.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.id;dialog.close();showDetails(id);}));dialog.showModal();
}
document.querySelector('#add-account').addEventListener('click',()=>{editingId=null;const f=document.querySelector('#account-form');f.reset();f.elements.billingAccountId.disabled=false;f.elements.keyFile.required=true;document.querySelector('#dialog-title').textContent='Добавить аккаунт';document.querySelector('#key-hint').textContent='Загрузите JSON-ключ сервисного аккаунта (id, service_account_id, private_key).';document.querySelector('#form-error').textContent='';document.querySelector('#account-dialog').showModal();});
for(const id of ['dialog-close','dialog-cancel'])document.querySelector(`#${id}`).addEventListener('click',()=>document.querySelector('#account-dialog').close());
for(const id of ['detail-close','detail-dismiss'])document.querySelector(`#${id}`).addEventListener('click',()=>document.querySelector('#detail-dialog').close());
document.querySelector('#overview-close').addEventListener('click',()=>document.querySelector('#overview-dialog').close());
for(const [id,kind] of [['summary-accounts-card','accounts'],['summary-cdn-card','cdn'],['summary-spent-card','grants'],['summary-remaining-card','grants']]){const card=document.querySelector(`#${id}`);card.addEventListener('click',()=>openOverview(kind));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openOverview(kind);}});}
function applyTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('#theme-icon').textContent=dark?'☀':'☾';document.querySelector('#theme-label').textContent=dark?'Светлая тема':'Тёмная тема';document.querySelector('#theme-toggle').setAttribute('aria-pressed',String(dark));try{localStorage.setItem('yc-monitor-theme',dark?'dark':'light')}catch{}}
let savedTheme='light';try{savedTheme=localStorage.getItem('yc-monitor-theme')||'light'}catch{}applyTheme(savedTheme);
document.querySelector('#theme-toggle').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
document.querySelector('#detail-edit').addEventListener('click',e=>{const id=e.currentTarget.dataset.id;document.querySelector('#detail-dialog').close();openEdit(id);});
document.querySelector('#account-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,error=document.querySelector('#form-error');error.textContent='';try{
  const folders=f.elements.folders.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const parts=line.split(',').map(x=>x.trim());if(parts.length!==2)throw new Error('Каждая строка каталогов должна быть в формате cloud-id,folder-id.');return {cloudId:parts[0],folderId:parts[1]};});
  const body={name:f.elements.name.value,billingAccountId:f.elements.billingAccountId.value,grantStartDate:f.elements.grantStartDate.value,folders};const file=f.elements.keyFile.files[0];if(file)body.keyJson=JSON.parse(await file.text());
  const response=await fetch(editingId?`/api/accounts/${encodeURIComponent(editingId)}`:'/api/accounts',{method:editingId?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не удалось сохранить аккаунт.');document.querySelector('#account-dialog').close();await load();
}catch(err){error.textContent=err.message;}});
document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLocaleLowerCase('ru');[...rows.querySelectorAll('tr')].forEach(row=>row.hidden=!row.textContent.toLocaleLowerCase('ru').includes(q));});
document.querySelector('#refresh').addEventListener('click',async e=>{const b=e.currentTarget;b.classList.add('busy');b.disabled=true;try{await fetch('/api/refresh',{method:'POST'});await new Promise(r=>setTimeout(r,900));await load();}finally{b.classList.remove('busy');b.disabled=false;}});
load();setInterval(load,60000);
